name:                first
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/first#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2021 Author name here
category:            Web

dependencies:
  - base >= 4.7 && < 5
  - template-haskell
  - directory

library:
  source-dirs:      src
